### PR TITLE
Updating libs and docs

### PR DESCRIPTION
**Pull request by ricardohbin**
This PR upgrade both files - and fixes minor errors in documentation.

I am testing them a lot - and alI is working as expected without side effects.

But, it can be prudent this version release is `major`, what do you think?

### CODE REVIEW

**Comment by thanpolas** [comment]
That looks great @ricardohbin thank you!

I agree with the Major release so as to hint at what's involved, would you mind also changing the changelog at the bottom of README and credit yourself as per all other entries?

Cheers

**Comment by ricardohbin** [comment]
No problem. I can improve the code samples too. And about the build? What do you think about a

**Comment by ricardohbin** [comment]
Ready @thanpolas :)

I was thinking about updating some samples with `async/await` in README.md too, but I can put in other PR

**Comment by thanpolas** [comment]
Thank you @ricardohbin! v1.0.0 is now on npm

**Pull request merged**
